# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  use_frameworks!

target 'DocumentDirectoryExample' do
  pod "GCDWebServer", "~> 3.0"
  pod "GCDWebServer/WebUploader", "~> 3.0"
end
